using MagicCarRepairAISupported.Domain.Entities;
using MagicCarRepairAISupported.Domain.Enums;

namespace MagicCarRepairAISupported.Persistence.Seeds
{
    public static class WorkOrderSeedData
    {
        public static List<MagicCarRepairAISupported.Domain.Entities.WorkOrder> GetWorkOrders()
        {
            var now = DateTime.UtcNow;
            
            return new List<MagicCarRepairAISupported.Domain.Entities.WorkOrder>
            {
                // Completed Work Orders (Delivered)
                new MagicCarRepairAISupported.Domain.Entities.WorkOrder
                {
                    Id = 1,
                    WorkOrderNumber = $"WO-{now.AddDays(-30):yyyyMMdd}-0001",
                    VehicleId = 1,
                    CustomerId = 1,
                    EntryDate = now.AddDays(-30),
                    EstimatedDeliveryDate = now.AddDays(-28),
                    ActualDeliveryDate = now.AddDays(-28),
                    Status = WorkOrderStatus.Delivered,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 45000,
                    FuelLevel = 75,
                    SubTotal = 2500m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 450m,
                    TotalAmount = 2950m,
                    EstimatedCost = 3000m,
                    PaidAmount = 2950m,
                    PaymentStatus = PaymentStatus.Paid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-29),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-30),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 2,
                    WorkOrderNumber = $"WO-{now.AddDays(-25):yyyyMMdd}-0002",
                    VehicleId = 3,
                    CustomerId = 2,
                    EntryDate = now.AddDays(-25),
                    EstimatedDeliveryDate = now.AddDays(-23),
                    ActualDeliveryDate = now.AddDays(-23),
                    Status = WorkOrderStatus.Delivered,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 28000,
                    FuelLevel = 80,
                    SubTotal = 1800m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 324m,
                    TotalAmount = 2124m,
                    EstimatedCost = 2200m,
                    PaidAmount = 2124m,
                    PaymentStatus = PaymentStatus.Paid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-24),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-25),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 3,
                    WorkOrderNumber = $"WO-{now.AddDays(-20):yyyyMMdd}-0003",
                    VehicleId = 4,
                    CustomerId = 3,
                    EntryDate = now.AddDays(-20),
                    EstimatedDeliveryDate = now.AddDays(-18),
                    ActualDeliveryDate = now.AddDays(-18),
                    Status = WorkOrderStatus.Delivered,
                    Priority = WorkOrderPriority.High,
                    Kilometers = 67000,
                    FuelLevel = 60,
                    SubTotal = 3200m,
                    DiscountAmount = 160m,
                    DiscountPercentage = 5m,
                    TaxAmount = 608m,
                    TotalAmount = 3048m,
                    PaidAmount = 3048m,
                    PaymentStatus = PaymentStatus.Paid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-19),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-20),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 4,
                    WorkOrderNumber = $"WO-{now.AddDays(-15):yyyyMMdd}-0004",
                    VehicleId = 5,
                    CustomerId = 4,
                    EntryDate = now.AddDays(-15),
                    EstimatedDeliveryDate = now.AddDays(-13),
                    ActualDeliveryDate = now.AddDays(-13),
                    Status = WorkOrderStatus.Delivered,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 38000,
                    FuelLevel = 70,
                    SubTotal = 1500m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 270m,
                    TotalAmount = 1770m,
                    PaidAmount = 1770m,
                    PaymentStatus = PaymentStatus.Paid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-14),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-15),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 5,
                    WorkOrderNumber = $"WO-{now.AddDays(-10):yyyyMMdd}-0005",
                    VehicleId = 6,
                    CustomerId = 5,
                    EntryDate = now.AddDays(-10),
                    EstimatedDeliveryDate = now.AddDays(-8),
                    ActualDeliveryDate = now.AddDays(-8),
                    Status = WorkOrderStatus.Delivered,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 55000,
                    FuelLevel = 65,
                    SubTotal = 2200m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 396m,
                    TotalAmount = 2596m,
                    PaidAmount = 2596m,
                    PaymentStatus = PaymentStatus.Paid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-9),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-10),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 6,
                    WorkOrderNumber = $"WO-{now.AddDays(-5):yyyyMMdd}-0006",
                    VehicleId = 7,
                    CustomerId = 6,
                    EntryDate = now.AddDays(-5),
                    EstimatedDeliveryDate = now.AddDays(-3),
                    ActualDeliveryDate = now.AddDays(-3),
                    Status = WorkOrderStatus.Delivered,
                    Priority = WorkOrderPriority.High,
                    Kilometers = 25000,
                    FuelLevel = 85,
                    SubTotal = 4500m,
                    DiscountAmount = 225m,
                    DiscountPercentage = 5m,
                    TaxAmount = 855m,
                    TotalAmount = 5130m,
                    PaidAmount = 5130m,
                    PaymentStatus = PaymentStatus.Paid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-4),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-5),
                    CreatedBy = 1
                },
                
                // Repairing Work Orders (InProgress, InRepair, DiagnosisCompleted, QualityControl, Washing)
                new WorkOrder
                {
                    Id = 7,
                    WorkOrderNumber = $"WO-{now.AddDays(-7):yyyyMMdd}-0007",
                    VehicleId = 8,
                    CustomerId = 7,
                    EntryDate = now.AddDays(-7),
                    EstimatedDeliveryDate = now.AddDays(-2),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.InProgress,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 42000,
                    FuelLevel = 50,
                    SubTotal = 1800m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 324m,
                    TotalAmount = 2124m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-6),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-7),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 8,
                    WorkOrderNumber = $"WO-{now.AddDays(-6):yyyyMMdd}-0008",
                    VehicleId = 9,
                    CustomerId = 8,
                    EntryDate = now.AddDays(-6),
                    EstimatedDeliveryDate = now.AddDays(-1),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.InRepair,
                    Priority = WorkOrderPriority.High,
                    Kilometers = 48000,
                    FuelLevel = 55,
                    SubTotal = 2800m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 504m,
                    TotalAmount = 3304m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-5),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-6),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 9,
                    WorkOrderNumber = $"WO-{now.AddDays(-4):yyyyMMdd}-0009",
                    VehicleId = 10,
                    CustomerId = 2,
                    EntryDate = now.AddDays(-4),
                    EstimatedDeliveryDate = now.AddDays(1),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.DiagnosisCompleted,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 89000,
                    FuelLevel = 40,
                    SubTotal = 1200m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 216m,
                    TotalAmount = 1416m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-3),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-4),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 10,
                    WorkOrderNumber = $"WO-{now.AddDays(-3):yyyyMMdd}-0010",
                    VehicleId = 11,
                    CustomerId = 3,
                    EntryDate = now.AddDays(-3),
                    EstimatedDeliveryDate = now.AddDays(2),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.QualityControl,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 72000,
                    FuelLevel = 45,
                    SubTotal = 2100m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 378m,
                    TotalAmount = 2478m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-2),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-3),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 11,
                    WorkOrderNumber = $"WO-{now.AddDays(-2):yyyyMMdd}-0011",
                    VehicleId = 1,
                    CustomerId = 1,
                    EntryDate = now.AddDays(-2),
                    EstimatedDeliveryDate = now.AddDays(3),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.Washing,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 45500,
                    FuelLevel = 70,
                    SubTotal = 800m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 144m,
                    TotalAmount = 944m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-1),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-2),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 12,
                    WorkOrderNumber = $"WO-{now.AddDays(-1):yyyyMMdd}-0012",
                    VehicleId = 4,
                    CustomerId = 3,
                    EntryDate = now.AddDays(-1),
                    EstimatedDeliveryDate = now.AddDays(4),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.InProgress,
                    Priority = WorkOrderPriority.High,
                    Kilometers = 67200,
                    FuelLevel = 60,
                    SubTotal = 3500m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 630m,
                    TotalAmount = 4130m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddHours(-12),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-1),
                    CreatedBy = 1
                },
                
                // Waiting Work Orders (VehicleEntered, AppointmentScheduled, WaitingForParts, ReadyForDelivery)
                new WorkOrder
                {
                    Id = 13,
                    WorkOrderNumber = $"WO-{now:yyyyMMdd}-0013",
                    VehicleId = 2,
                    CustomerId = 1,
                    EntryDate = now,
                    EstimatedDeliveryDate = now.AddDays(5),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.VehicleEntered,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 52500,
                    FuelLevel = 65,
                    SubTotal = 0m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 0m,
                    TotalAmount = 0m,
                    EstimatedCost = 1200m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = null,
                    CustomerApprovalDate = null,
                    ClientId = 1,
                    CreatedDate = now,
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 14,
                    WorkOrderNumber = $"WO-{now.AddDays(1):yyyyMMdd}-0014",
                    VehicleId = 5,
                    CustomerId = 4,
                    EntryDate = now.AddDays(1),
                    EstimatedDeliveryDate = now.AddDays(6),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.AppointmentScheduled,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 38200,
                    FuelLevel = 75,
                    SubTotal = 0m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 0m,
                    TotalAmount = 0m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = null,
                    CustomerApprovalDate = null,
                    ClientId = 1,
                    CreatedDate = now.AddDays(1),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 15,
                    WorkOrderNumber = $"WO-{now.AddDays(-8):yyyyMMdd}-0015",
                    VehicleId = 6,
                    CustomerId = 5,
                    EntryDate = now.AddDays(-8),
                    EstimatedDeliveryDate = now.AddDays(-5),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.WaitingForParts,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 55200,
                    FuelLevel = 50,
                    SubTotal = 1900m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 342m,
                    TotalAmount = 2242m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddDays(-7),
                    ClientId = 1,
                    CreatedDate = now.AddDays(-8),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 16,
                    WorkOrderNumber = $"WO-{now.AddHours(-12):yyyyMMdd}-0016",
                    VehicleId = 7,
                    CustomerId = 6,
                    EntryDate = now.AddHours(-12),
                    EstimatedDeliveryDate = now.AddDays(1),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.ReadyForDelivery,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 25100,
                    FuelLevel = 80,
                    SubTotal = 1600m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 288m,
                    TotalAmount = 1888m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = CustomerApprovalStatus.Approved,
                    CustomerApprovalDate = now.AddHours(-10),
                    ClientId = 1,
                    CreatedDate = now.AddHours(-12),
                    CreatedBy = 1
                },
                new WorkOrder
                {
                    Id = 17,
                    WorkOrderNumber = $"WO-{now.AddHours(-6):yyyyMMdd}-0017",
                    VehicleId = 8,
                    CustomerId = 7,
                    EntryDate = now.AddHours(-6),
                    EstimatedDeliveryDate = now.AddDays(2),
                    ActualDeliveryDate = null,
                    Status = WorkOrderStatus.VehicleEntered,
                    Priority = WorkOrderPriority.Normal,
                    Kilometers = 42100,
                    FuelLevel = 55,
                    SubTotal = 0m,
                    DiscountAmount = 0m,
                    DiscountPercentage = 0m,
                    TaxAmount = 0m,
                    TotalAmount = 0m,
                    PaidAmount = 0m,
                    PaymentStatus = PaymentStatus.Unpaid,
                    CustomerApprovalStatus = null,
                    CustomerApprovalDate = null,
                    ClientId = 1,
                    CreatedDate = now.AddHours(-6),
                    CreatedBy = 1
                }
            };
        }

        public static void SeedWorkOrders(this Microsoft.EntityFrameworkCore.ModelBuilder builder)
        {
            builder.Entity<WorkOrder>().HasData(GetWorkOrders());
        }
    }
}
