// <auto-generated />
using MagicCarRepairAISupported.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MagicCarRepairAISupported.Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260527120000_FixRoleMultiTenantUniqueIndex")]
    partial class FixRoleMultiTenantUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Index-only migration; authoritative model is BaseDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
